apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T06:54:10Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1814"
  uid: 8f0a68e8-c751-40fb-ae6c-263b0825025b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.130.123
  clusterIPs:
  - 10.102.130.123
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31695
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
